name: Auto Black

on: [pull_request, push]

jobs:
  autoblack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - uses: actions/setup-python@v1

      - run: pip install black

      - name: autoblack_check
        id: black-check
        run: black --check .
